### PR TITLE
REST API Resource for UserPrice

### PR DESCRIPTION
**Pull request by mgaerber**
Adds REST API endpoints for user prices and user price groups.

### CODE REVIEW

**Comment by Baysen** [comment]
Any Chance for this to be merged soon? This is exactly what I need for my project right now :)

**Comment by mitelg** [comment]
@RemizZ I would not recommend to wait for this PR. Unfortunately this plugin has no priority at the moment. Nevertheless you could still adapt this to your custom project

**Comment by mgaerber** [comment]
@RemizZ you could just clone or fork from here https://github.com/axxepta/SwagUserPrice

We have this in production for several months now.

**Comment by Baysen** [comment]
@mitelg If this is no priority for your team at all, might you consider giving it to the community so we can improve it ourselves? Waiting for official releases just for a small PR seems unnessesary.

@mgaerber thank you! You saved me a lot of time. Could you update it to match the newest version? Doesn't seem to be compatible with 5.5 anymore.

**Comment by mitelg** [comment]
@RemizZ what do you mean by "giving it to the community" ? :blush: 
the plugin is available for free in the store and the source code is here in GitHub. Did I miss something?

**Comment by Baysen** [comment]
@mitelg Letting trusted people from the community process those pull requests for you, so you don't have to put in the time is what I meant :)

**Comment by mitelg** [comment]
@RemizZ ah now I see :blush: 
I will put this discussion in to place!

**Comment by mitelg** [comment]
hey @mgaerber 

Sorry for the late answer!
The corresponding ticket was closed. If this change is still relevant for you, please feel free to create a new PR.

**Pull request closed without merging**
