### PR TITLE
fix exception on console

### PR DESCRIPTION
**Pull request by resslinger**
see under http://issues.shopware.com/issues/PT-7366

### CODE REVIEW

**Comment by mitelg** [comment]
thanks for your PR @k-30 :+1: 

we scheduled the ticket in our workflow.

**Comment by shyim** [comment]
Any updates here. We got a support ticket for our payment reminder plugin for a exception introduced this problem

**Comment by shyim** [comment]
If i would get shopware_storefront.graduated_prices_service and shopware_storefront.cheapest_price_service from container it would execute onStartDispatch twice and subscribers would be registered also twice..

**Comment by resslinger** [comment]
What do you think about it, to move the execute onStartDispatch to the method afterInit? so it should be called once.

**Comment by tinect** [comment]
@mitelg any progress here?

**Comment by mitelg** [comment]
hey guys, 
sorry for the delay on this ticket! currently the ticket is planned for one of the next sprints, but not yet to a specific one :-) 
Also the comment of @shyim is something we should think of ;-) Maybe you can adapt your PR @k-30 ?

**Pull request closed without merging**
